// <auto-generated />
namespace PlainsOfPrimus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Character : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Character));
        
        string IMigrationMetadata.Id
        {
            get { return "202101171928108_Character"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
